from __future__ import annotations

from collections.abc import Iterable

SchemaSpec = dict[str, str]


def empty_relation_sql(columns: SchemaSpec) -> str:
    parts = [f"CAST(NULL AS {dtype}) AS {name}" for name, dtype in columns.items()]
    return "SELECT " + ", ".join(parts) + " WHERE FALSE"


CANONICAL_SCHEMAS: dict[str, SchemaSpec] = {
    "macro_observations": {
        "series_id": "VARCHAR",
        "observation_date": "DATE",
        "value": "DOUBLE",
        "realtime_start": "DATE",
        "realtime_end": "DATE",
        "known_at": "TIMESTAMP WITH TIME ZONE",
        "source_snapshot": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "macro_vintages": {
        "series_id": "VARCHAR",
        "observation_date": "DATE",
        "value": "DOUBLE",
        "realtime_start": "DATE",
        "realtime_end": "DATE",
        "known_at": "TIMESTAMP WITH TIME ZONE",
        "source_snapshot": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "edgar_submissions": {
        "cik": "VARCHAR",
        "company_name": "VARCHAR",
        "accession_number": "VARCHAR",
        "form": "VARCHAR",
        "filing_date": "DATE",
        "acceptance_datetime": "TIMESTAMP WITH TIME ZONE",
        "primary_document": "VARCHAR",
        "primary_doc_description": "VARCHAR",
        "snapshot_at": "TIMESTAMP WITH TIME ZONE",
        "source_snapshot": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "edgar_companyfacts": {
        "cik": "VARCHAR",
        "entity_name": "VARCHAR",
        "taxonomy": "VARCHAR",
        "metric_name": "VARCHAR",
        "unit": "VARCHAR",
        "value": "DOUBLE",
        "period_end": "DATE",
        "filing_date": "DATE",
        "frame": "VARCHAR",
        "fy": "INTEGER",
        "fp": "VARCHAR",
        "form": "VARCHAR",
        "snapshot_at": "TIMESTAMP WITH TIME ZONE",
        "source_snapshot": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "filing_index": {
        "cik": "VARCHAR",
        "accession_number": "VARCHAR",
        "form": "VARCHAR",
        "filing_date": "DATE",
        "acceptance_datetime": "TIMESTAMP WITH TIME ZONE",
        "primary_document": "VARCHAR",
        "primary_doc_description": "VARCHAR",
        "snapshot_at": "TIMESTAMP WITH TIME ZONE",
        "source_snapshot": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "prices": {
        "ticker": "VARCHAR",
        "date": "DATE",
        "open": "DOUBLE",
        "high": "DOUBLE",
        "low": "DOUBLE",
        "close": "DOUBLE",
        "adj_close": "DOUBLE",
        "adj_open": "DOUBLE",
        "adj_high": "DOUBLE",
        "adj_low": "DOUBLE",
        "adj_volume": "DOUBLE",
        "volume": "DOUBLE",
        "div_cash": "DOUBLE",
        "split_factor": "DOUBLE",
        "known_at": "TIMESTAMP WITH TIME ZONE",
        "source_snapshot": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "price_actions": {
        "ticker": "VARCHAR",
        "date": "DATE",
        "div_cash": "DOUBLE",
        "split_factor": "DOUBLE",
        "known_at": "TIMESTAMP WITH TIME ZONE",
        "source_snapshot": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "universe_membership": {
        "as_of_date": "DATE",
        "ticker": "VARCHAR",
        "security": "VARCHAR",
        "sector": "VARCHAR",
        "sub_industry": "VARCHAR",
        "cik": "VARCHAR",
        "snapshot_at": "TIMESTAMP WITH TIME ZONE",
        "source_snapshot": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "v1_universe": {
        "as_of_date": "DATE",
        "ticker": "VARCHAR",
        "security": "VARCHAR",
        "sector": "VARCHAR",
        "sub_industry": "VARCHAR",
        "cik": "VARCHAR",
        "avg_dollar_volume_60d": "DOUBLE",
        "universe_rank": "INTEGER",
        "snapshot_at": "TIMESTAMP WITH TIME ZONE",
        "source_snapshot": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "feature_matrix": {
        "date": "DATE",
        "ticker": "VARCHAR",
        "sector": "VARCHAR",
        "ret_1d": "DOUBLE",
        "ret_5d": "DOUBLE",
        "ret_20d": "DOUBLE",
        "ret_60d": "DOUBLE",
        "overnight_gap": "DOUBLE",
        "range_norm": "DOUBLE",
        "realized_vol_20d": "DOUBLE",
        "volume_surprise_20d": "DOUBLE",
        "share_turnover": "DOUBLE",
        "oil_supply_risk_1d": "DOUBLE",
        "gas_supply_risk_1d": "DOUBLE",
        "shipping_stress_1d": "DOUBLE",
        "sanctions_pressure_1d": "DOUBLE",
        "defense_escalation_1d": "DOUBLE",
        "grid_stress_1d": "DOUBLE",
        "cyber_infra_risk_1d": "DOUBLE",
        "policy_relief_prob_1d": "DOUBLE",
        "commodity_shock_score": "DOUBLE",
        "geo_novelty_score": "DOUBLE",
        "regional_concentration_risk": "DOUBLE",
        "sector_context_shock": "DOUBLE",
        "stock_context_shock": "DOUBLE",
        "analog_match_score": "DOUBLE",
        "analog_failure_risk": "DOUBLE",
        "regime_score": "DOUBLE",
        "regime_is_escalating": "DOUBLE",
        "theme_convergence_score": "DOUBLE",
        "pricing_geo_signal_strength": "DOUBLE",
        "pricing_mediator_confirmation": "DOUBLE",
        "pricing_market_response_strength": "DOUBLE",
        "pricing_divergence_score": "DOUBLE",
        "pricing_crowdedness_proxy": "DOUBLE",
        "pricing_follow_through_status": "DOUBLE",
        "causal_chain_count": "DOUBLE",
        "causal_chain_avg_confidence": "DOUBLE",
        "causal_net_sign": "DOUBLE",
        "source_reliability_score": "DOUBLE",
        "source_claim_verifiability": "DOUBLE",
        "source_freshness_score": "DOUBLE",
        "narrative_deception_risk": "DOUBLE",
        "narrative_actionability_score": "DOUBLE",
        "narrative_novelty_score": "DOUBLE",
        "cross_asset_energy_confirmation": "DOUBLE",
        "cross_asset_vol_confirmation": "DOUBLE",
        "cross_asset_credit_confirmation": "DOUBLE",
        "cross_asset_rates_confirmation": "DOUBLE",
        "cross_asset_fx_confirmation": "DOUBLE",
        "cross_asset_sector_flow_confirmation": "DOUBLE",
        "cross_asset_peer_confirmation": "DOUBLE",
        "cross_asset_aggregate_confirmation": "DOUBLE",
        "pricing_discipline_market_confirmation": "DOUBLE",
        "pricing_discipline_move_lateness": "DOUBLE",
        "pricing_discipline_overextension": "DOUBLE",
        "pricing_discipline_reaction_follow_through": "DOUBLE",
        "trade_readiness_thesis_validity": "DOUBLE",
        "trade_readiness_pricing_alignment": "DOUBLE",
        "trade_readiness_timing_quality": "DOUBLE",
        "trade_readiness_liquidity_quality": "DOUBLE",
        "trade_readiness_risk_reward_quality": "DOUBLE",
        "event_dispersion_score": "DOUBLE",
        "known_at": "TIMESTAMP WITH TIME ZONE",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "label_matrix": {
        "date": "DATE",
        "ticker": "VARCHAR",
        "return_5d": "DOUBLE",
        "benchmark_return_5d": "DOUBLE",
        "excess_alpha_5d": "DOUBLE",
        "excess_alpha_rank": "DOUBLE",
        "known_at": "TIMESTAMP WITH TIME ZONE",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "events": {
        "event_time": "TIMESTAMP WITH TIME ZONE",
        "ingest_time": "TIMESTAMP WITH TIME ZONE",
        "source": "VARCHAR",
        "topic": "VARCHAR",
        "severity": "DOUBLE",
        "novelty": "DOUBLE",
        "confidence": "DOUBLE",
        "affected_entities": "VARCHAR[]",
        "geography": "VARCHAR",
        "theme": "VARCHAR",
        "market_relevance": "DOUBLE",
        "raw_ref": "VARCHAR",
    },
    "normalized_events": {
        "event_id": "VARCHAR",
        "event_time": "TIMESTAMP WITH TIME ZONE",
        "ingest_time": "TIMESTAMP WITH TIME ZONE",
        "source": "VARCHAR",
        "topic": "VARCHAR",
        "event_family": "VARCHAR",
        "theme": "VARCHAR",
        "region": "VARCHAR",
        "geography": "VARCHAR",
        "severity": "DOUBLE",
        "confidence": "DOUBLE",
        "novelty": "DOUBLE",
        "duration_hours": "DOUBLE",
        "market_relevance": "DOUBLE",
        "affected_commodities": "VARCHAR[]",
        "affected_sectors": "VARCHAR[]",
        "affected_entities": "VARCHAR[]",
        "raw_ref": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "event_entities": {
        "event_id": "VARCHAR",
        "entity_type": "VARCHAR",
        "entity_id": "VARCHAR",
        "entity_name": "VARCHAR",
        "entity_role": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "event_relations": {
        "event_id": "VARCHAR",
        "source_type": "VARCHAR",
        "source_id": "VARCHAR",
        "relation_type": "VARCHAR",
        "target_type": "VARCHAR",
        "target_id": "VARCHAR",
        "confidence": "DOUBLE",
        "evidence_text": "VARCHAR",
        "theme": "VARCHAR",
        "region": "VARCHAR",
        "market_relevance": "DOUBLE",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "event_source_assessment": {
        "event_id": "VARCHAR",
        "source": "VARCHAR",
        "reliability_score": "DOUBLE",
        "claim_verifiability": "DOUBLE",
        "source_grade": "VARCHAR",
        "freshness_score": "DOUBLE",
        "provenance_quality": "DOUBLE",
        "assessment_summary": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "event_narrative_risk": {
        "event_id": "VARCHAR",
        "source": "VARCHAR",
        "deception_risk": "DOUBLE",
        "signaling_vs_capability": "DOUBLE",
        "novelty_score": "DOUBLE",
        "actionability_score": "DOUBLE",
        "repetition_decay": "DOUBLE",
        "propaganda_risk": "DOUBLE",
        "risk_summary": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "evidence_catalog": {
        "evidence_id": "VARCHAR",
        "event_id": "VARCHAR",
        "source_type": "VARCHAR",
        "source_ref": "VARCHAR",
        "timestamp": "TIMESTAMP WITH TIME ZONE",
        "reliability": "DOUBLE",
        "freshness_class": "VARCHAR",
        "content_hash": "VARCHAR",
        "content_preview": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "dependency_markers": {
        "source_type": "VARCHAR",
        "source_id": "VARCHAR",
        "relation_type": "VARCHAR",
        "target_type": "VARCHAR",
        "target_id": "VARCHAR",
        "weight": "DOUBLE",
        "rationale": "VARCHAR",
        "source": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "theme_intensity_hourly": {
        "bucket_time": "TIMESTAMP WITH TIME ZONE",
        "theme": "VARCHAR",
        "intensity": "DOUBLE",
        "event_count": "INTEGER",
        "avg_severity": "DOUBLE",
        "avg_novelty": "DOUBLE",
        "event_dispersion_score": "DOUBLE",
        "latest_event_time": "TIMESTAMP WITH TIME ZONE",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "theme_intensity_daily": {
        "date": "DATE",
        "theme": "VARCHAR",
        "intensity": "DOUBLE",
        "event_count": "INTEGER",
        "avg_severity": "DOUBLE",
        "avg_novelty": "DOUBLE",
        "event_dispersion_score": "DOUBLE",
        "latest_event_time": "TIMESTAMP WITH TIME ZONE",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "sector_theme_exposure": {
        "sector": "VARCHAR",
        "theme": "VARCHAR",
        "exposure": "DOUBLE",
        "transmission_label": "VARCHAR",
        "rationale": "VARCHAR",
        "source": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "industry_theme_exposure": {
        "industry": "VARCHAR",
        "theme": "VARCHAR",
        "exposure": "DOUBLE",
        "transmission_label": "VARCHAR",
        "rationale": "VARCHAR",
        "source": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "stock_theme_exposure": {
        "ticker": "VARCHAR",
        "theme": "VARCHAR",
        "exposure": "DOUBLE",
        "transmission_label": "VARCHAR",
        "rationale": "VARCHAR",
        "source": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "sector_rankings": {
        "as_of_date": "DATE",
        "sector": "VARCHAR",
        "sector_score": "DOUBLE",
        "context_shock": "DOUBLE",
        "finance_score": "DOUBLE",
        "rank_desc": "INTEGER",
        "rank_asc": "INTEGER",
        "top_theme": "VARCHAR",
        "supporting_themes": "VARCHAR[]",
        "solution_bucket": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "theme_regimes": {
        "as_of_date": "DATE",
        "theme": "VARCHAR",
        "regime_name": "VARCHAR",
        "regime_score": "DOUBLE",
        "source": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "historical_analogs": {
        "as_of_date": "DATE",
        "analog_type": "VARCHAR",
        "anchor_key": "VARCHAR",
        "analog_key": "VARCHAR",
        "analog_start": "DATE",
        "analog_end": "DATE",
        "similarity_score": "DOUBLE",
        "thesis": "VARCHAR",
        "raw_ref": "VARCHAR",
        "important_differences": "VARCHAR[]",
        "analogy_strength": "VARCHAR",
        "misleading_analogy": "BOOLEAN",
        "non_analog_reasons": "VARCHAR[]",
        "analogy_failure_risk": "DOUBLE",
        "forward_outcomes": "JSON",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "cross_asset_confirmation_daily": {
        "as_of_date": "DATE",
        "confirmation_key": "VARCHAR",
        "value": "DOUBLE",
        "confidence": "DOUBLE",
        "status": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "pricing_discipline_daily": {
        "as_of_date": "DATE",
        "discipline_key": "VARCHAR",
        "value": "DOUBLE",
        "confidence": "DOUBLE",
        "status": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "trade_readiness_daily": {
        "as_of_date": "DATE",
        "readiness_key": "VARCHAR",
        "value": "DOUBLE",
        "confidence": "DOUBLE",
        "status": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "causal_state_daily": {
        "as_of_date": "DATE",
        "state_key": "VARCHAR",
        "state_value": "VARCHAR",
        "state_confidence": "DOUBLE",
        "state_status": "VARCHAR",
        "graph_version": "VARCHAR",
        "causal_state_version": "VARCHAR",
        "reasoning_schema_version": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "causal_chain_activations": {
        "as_of_date": "DATE",
        "source_event_id": "VARCHAR",
        "theme": "VARCHAR",
        "channel": "VARCHAR",
        "mediator": "VARCHAR",
        "sector": "VARCHAR",
        "ticker": "VARCHAR",
        "sign": "INTEGER",
        "weight": "DOUBLE",
        "lag_days_min": "INTEGER",
        "lag_days_max": "INTEGER",
        "activation_confidence": "DOUBLE",
        "activation_status": "VARCHAR",
        "deterministic_edge": "BOOLEAN",
        "rationale": "VARCHAR",
        "graph_version": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "solution_mappings": {
        "theme": "VARCHAR",
        "solution_type": "VARCHAR",
        "label": "VARCHAR",
        "beneficiary_sector": "VARCHAR",
        "hedge_role": "VARCHAR",
        "rationale": "VARCHAR",
        "source": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "entity_company": {
        "entity_id": "VARCHAR",
        "ticker": "VARCHAR",
        "name": "VARCHAR",
        "sector": "VARCHAR",
        "country": "VARCHAR",
        "source": "VARCHAR",
    },
    "entity_country": {
        "entity_id": "VARCHAR",
        "country_code": "VARCHAR",
        "name": "VARCHAR",
        "region": "VARCHAR",
        "source": "VARCHAR",
    },
    "entity_region": {
        "entity_id": "VARCHAR",
        "name": "VARCHAR",
        "source": "VARCHAR",
    },
    "entity_commodity": {
        "entity_id": "VARCHAR",
        "symbol": "VARCHAR",
        "name": "VARCHAR",
        "source": "VARCHAR",
    },
    "entity_sector": {
        "entity_id": "VARCHAR",
        "name": "VARCHAR",
        "source": "VARCHAR",
    },
    "entity_route": {
        "entity_id": "VARCHAR",
        "name": "VARCHAR",
        "source": "VARCHAR",
    },
    "entity_event_type": {
        "entity_id": "VARCHAR",
        "name": "VARCHAR",
        "source": "VARCHAR",
    },
    "entity_policy_action": {
        "entity_id": "VARCHAR",
        "name": "VARCHAR",
        "source": "VARCHAR",
    },
    "forecast_outcomes": {
        "forecast_id": "VARCHAR",
        "ticker": "VARCHAR",
        "as_of": "TIMESTAMP WITH TIME ZONE",
        "mode": "VARCHAR",
        "requested_mode": "VARCHAR",
        "resolved_mode": "VARCHAR",
        "trust_tier": "VARCHAR",
        "horizon": "VARCHAR",
        "direction": "VARCHAR",
        "confidence": "DOUBLE",
        "decision_confidence_uncapped": "DOUBLE",
        "data_confidence": "DOUBLE",
        "state_confidence": "DOUBLE",
        "model_confidence": "DOUBLE",
        "pricing_confidence": "DOUBLE",
        "analog_confidence": "DOUBLE",
        "abstain": "BOOLEAN",
        "downgrade_reason_category": "VARCHAR",
        "invalidation_triggers": "VARCHAR[]",
        "critic_reason_codes": "VARCHAR[]",
        "evidence_hash": "VARCHAR",
        "freshness_summary": "JSON",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "forecast_calibration_metrics": {
        "as_of_date": "DATE",
        "metric_name": "VARCHAR",
        "metric_value": "DOUBLE",
        "metric_bucket": "VARCHAR",
        "source": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "llm_override_log": {
        "forecast_id": "VARCHAR",
        "ticker": "VARCHAR",
        "as_of": "TIMESTAMP WITH TIME ZONE",
        "override_applied": "BOOLEAN",
        "override_reason": "VARCHAR",
        "requested_mode": "VARCHAR",
        "resolved_mode": "VARCHAR",
        "trust_tier": "VARCHAR",
        "downgrade_reason_category": "VARCHAR",
        "critic_reason_codes": "VARCHAR[]",
        "evidence_used": "VARCHAR[]",
        "final_direction": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
    "feature_family_ablation_metrics": {
        "as_of_date": "DATE",
        "feature_family": "VARCHAR",
        "metric_name": "VARCHAR",
        "metric_value": "DOUBLE",
        "source": "VARCHAR",
        "transform_loaded_at": "TIMESTAMP WITH TIME ZONE",
    },
}


def relation_names() -> Iterable[str]:
    return CANONICAL_SCHEMAS.keys()
